### ISSUE TITLE
gradients?

### ISSUE THREAD

**Issue by argyleink** [rodydavis/postcss-color-hct#2]
the `hct()` gradients are super nice, i'd love to use them! maybe it's a separate plugin even?

if gradients could be generated in hct and 3-6 points extracted from along it, you could probably get [rgb recreations](https://www.joshwcomeau.com/gradient-generator/) that would def be an improvement to the srgb ones of today.

be sweet to follow the draft spec syntax:

```css
.rad {
  background: linear-gradient(to right in hct, blue, white);
}
```
